### ISSUE TITLE
Make Internet.org Compliant

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/GotToVote-RCI#4]
_Ref: [Internet.org Technical Guidelines](https://developers.facebook.com/docs/internet-org/platform-technical-guidelines)_

This is a good opportunity as elections information should be available as easily as possible and for free.

**Pros:**
- Get ahead of the curve on internet.org integration.
- Good for almost-dumb phones that have internet access.
- Already very lightweight so easy to make move.
- Allows adding SSL to RCI component.
- We can provide an API to the data.
- Could allow consolidating all the modules onto one platform.

**Cons:**
- Cannot take advantage of free hosting with Github pages.
- JS disabling reduces overall user experience:
  - Page has to be reloaded each time there is a form submission.
  - Desktop users will lose out on smooth scroll etc.
- Adding analytics tracker might be tricky.

**Comment by DavidLemayian** [comment]
Realistically and easiest for most people to be able to contribute, we should probably keep it PHP. Python / Node.JS could be light-weight alternatives but would take longer to move.

Suggested framework: [Lumen by Laravel](http://lumen.laravel.com)

**Comment by matthewtrask** [comment]
Open to contributions?

**Comment by DavidLemayian** [comment]
@rocketpastsix Most definitely!

**Comment by matthewtrask** [comment]
Are you still wanting Laravel or Lumen?

Sorry, was busy with some other stuff, but I have some time now!

**Comment by DavidLemayian** [comment]
@rocketpastsix Not a hassle! Lumen seems like the better option. Lightweight to keep the app fast.

**Comment by matthewtrask** [comment]
Cool, Ill fork and start working. Got somethings you want to add before I start the conversion?

**Comment by DavidLemayian** [comment]
@rocketpastsix Nothing. I believe simplicity is key.

**Comment by matthewtrask** [comment]
Cool, well I'll be positing questions as I go.

**Comment by afturner** [comment]
@rocketpastsix What's the status on this? I'd be happy to work with you on this

**Comment by matthewtrask** [comment]
bits and pieces, @afturner but would love to work together. you can email me, mjftrask@gmail.com

**Comment by DavidLemayian** [comment]
Net neutrality is a fundamental idea that Internet.org definitely defies. We are therefore closing this issue but keeping to the original idea to allow the GotToVote toolkit to be accessible on devices that don't have javascript. The party continues [here](https://github.com/CodeForAfrica/GotToVote.cc/issues/4).
